# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'hw1UI.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1216, 498)
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(20, 20, 191, 311))
        self.groupBox.setObjectName("groupBox")
        self.button1_1 = QtWidgets.QPushButton(self.groupBox)
        self.button1_1.setGeometry(QtCore.QRect(20, 30, 161, 61))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.button1_1.setFont(font)
        self.button1_1.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.button1_1.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.button1_1.setAutoDefault(True)
        self.button1_1.setFlat(False)
        self.button1_1.setObjectName("button1_1")
        self.button1_2 = QtWidgets.QPushButton(self.groupBox)
        self.button1_2.setGeometry(QtCore.QRect(20, 100, 161, 61))
        self.button1_2.setObjectName("button1_2")
        self.button1_3 = QtWidgets.QPushButton(self.groupBox)
        self.button1_3.setGeometry(QtCore.QRect(20, 170, 161, 61))
        self.button1_3.setObjectName("button1_3")
        self.button1_4 = QtWidgets.QPushButton(self.groupBox)
        self.button1_4.setGeometry(QtCore.QRect(20, 240, 161, 61))
        self.button1_4.setObjectName("button1_4")
        self.groupBox_2 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_2.setGeometry(QtCore.QRect(220, 20, 191, 171))
        self.groupBox_2.setObjectName("groupBox_2")
        self.button2_1 = QtWidgets.QPushButton(self.groupBox_2)
        self.button2_1.setGeometry(QtCore.QRect(20, 30, 161, 61))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.button2_1.setFont(font)
        self.button2_1.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.button2_1.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.button2_1.setAutoDefault(True)
        self.button2_1.setFlat(False)
        self.button2_1.setObjectName("button2_1")
        self.button2_2 = QtWidgets.QPushButton(self.groupBox_2)
        self.button2_2.setGeometry(QtCore.QRect(20, 100, 161, 61))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.button2_2.setFont(font)
        self.button2_2.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.button2_2.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.button2_2.setAutoDefault(True)
        self.button2_2.setFlat(False)
        self.button2_2.setObjectName("button2_2")
        self.groupBox_3 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_3.setGeometry(QtCore.QRect(420, 20, 301, 371))
        self.groupBox_3.setObjectName("groupBox_3")
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox_4.setGeometry(QtCore.QRect(20, 30, 271, 281))
        self.groupBox_4.setObjectName("groupBox_4")
        self.groupBox_5 = QtWidgets.QGroupBox(self.groupBox_4)
        self.groupBox_5.setGeometry(QtCore.QRect(20, 30, 241, 191))
        self.groupBox_5.setObjectName("groupBox_5")
        self.label_2 = QtWidgets.QLabel(self.groupBox_5)
        self.label_2.setGeometry(QtCore.QRect(10, 40, 51, 17))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox_5)
        self.label_3.setGeometry(QtCore.QRect(10, 80, 51, 17))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox_5)
        self.label_4.setGeometry(QtCore.QRect(10, 120, 51, 17))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox_5)
        self.label_5.setGeometry(QtCore.QRect(10, 160, 51, 17))
        self.label_5.setObjectName("label_5")
        self.textEdit3_1 = QtWidgets.QTextEdit(self.groupBox_5)
        self.textEdit3_1.setGeometry(QtCore.QRect(60, 30, 104, 31))
        self.textEdit3_1.setObjectName("textEdit3_1")
        self.textEdit3_2 = QtWidgets.QTextEdit(self.groupBox_5)
        self.textEdit3_2.setGeometry(QtCore.QRect(60, 70, 104, 31))
        self.textEdit3_2.setObjectName("textEdit3_2")
        self.textEdit3_3 = QtWidgets.QTextEdit(self.groupBox_5)
        self.textEdit3_3.setGeometry(QtCore.QRect(60, 110, 104, 31))
        self.textEdit3_3.setObjectName("textEdit3_3")
        self.textEdit3_4 = QtWidgets.QTextEdit(self.groupBox_5)
        self.textEdit3_4.setGeometry(QtCore.QRect(60, 150, 104, 31))
        self.textEdit3_4.setObjectName("textEdit3_4")
        self.label_6 = QtWidgets.QLabel(self.groupBox_5)
        self.label_6.setGeometry(QtCore.QRect(170, 40, 51, 17))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.groupBox_5)
        self.label_7.setGeometry(QtCore.QRect(170, 120, 51, 17))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.groupBox_5)
        self.label_8.setGeometry(QtCore.QRect(170, 160, 51, 17))
        self.label_8.setObjectName("label_8")
        self.button3_1 = QtWidgets.QPushButton(self.groupBox_4)
        self.button3_1.setGeometry(QtCore.QRect(20, 230, 241, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.button3_1.setFont(font)
        self.button3_1.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.button3_1.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.button3_1.setAutoDefault(True)
        self.button3_1.setFlat(False)
        self.button3_1.setObjectName("button3_1")
        self.button3_2 = QtWidgets.QPushButton(self.groupBox_3)
        self.button3_2.setGeometry(QtCore.QRect(40, 320, 241, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.button3_2.setFont(font)
        self.button3_2.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.button3_2.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.button3_2.setAutoDefault(True)
        self.button3_2.setFlat(False)
        self.button3_2.setObjectName("button3_2")
        self.groupBox_6 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_6.setGeometry(QtCore.QRect(730, 20, 191, 311))
        self.groupBox_6.setObjectName("groupBox_6")
        self.button4_1 = QtWidgets.QPushButton(self.groupBox_6)
        self.button4_1.setGeometry(QtCore.QRect(20, 30, 161, 61))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.button4_1.setFont(font)
        self.button4_1.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.button4_1.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.button4_1.setAutoDefault(True)
        self.button4_1.setFlat(False)
        self.button4_1.setObjectName("button4_1")
        self.button4_2 = QtWidgets.QPushButton(self.groupBox_6)
        self.button4_2.setGeometry(QtCore.QRect(20, 100, 161, 61))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.button4_2.setFont(font)
        self.button4_2.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.button4_2.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.button4_2.setAutoDefault(True)
        self.button4_2.setFlat(False)
        self.button4_2.setObjectName("button4_2")
        self.button4_3 = QtWidgets.QPushButton(self.groupBox_6)
        self.button4_3.setGeometry(QtCore.QRect(20, 170, 161, 61))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.button4_3.setFont(font)
        self.button4_3.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.button4_3.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.button4_3.setAutoDefault(True)
        self.button4_3.setFlat(False)
        self.button4_3.setObjectName("button4_3")
        self.button4_4 = QtWidgets.QPushButton(self.groupBox_6)
        self.button4_4.setGeometry(QtCore.QRect(20, 240, 161, 61))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.button4_4.setFont(font)
        self.button4_4.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.button4_4.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.button4_4.setAutoDefault(True)
        self.button4_4.setFlat(False)
        self.button4_4.setObjectName("button4_4")
        self.groupBox_7 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_7.setGeometry(QtCore.QRect(930, 20, 271, 431))
        self.groupBox_7.setObjectName("groupBox_7")
        self.textEdit5_5 = QtWidgets.QTextEdit(self.groupBox_7)
        self.textEdit5_5.setGeometry(QtCore.QRect(150, 320, 111, 31))
        self.textEdit5_5.setObjectName("textEdit5_5")
        self.button5_1 = QtWidgets.QPushButton(self.groupBox_7)
        self.button5_1.setGeometry(QtCore.QRect(20, 30, 241, 61))
        self.button5_1.setObjectName("button5_1")
        self.button5_4 = QtWidgets.QPushButton(self.groupBox_7)
        self.button5_4.setGeometry(QtCore.QRect(20, 240, 241, 61))
        self.button5_4.setObjectName("button5_4")
        self.button5_2 = QtWidgets.QPushButton(self.groupBox_7)
        self.button5_2.setGeometry(QtCore.QRect(20, 100, 241, 61))
        self.button5_2.setObjectName("button5_2")
        self.button5_3 = QtWidgets.QPushButton(self.groupBox_7)
        self.button5_3.setGeometry(QtCore.QRect(20, 170, 241, 61))
        self.button5_3.setObjectName("button5_3")
        self.button5_5 = QtWidgets.QPushButton(self.groupBox_7)
        self.button5_5.setGeometry(QtCore.QRect(20, 360, 241, 61))
        self.button5_5.setObjectName("button5_5")
        self.label = QtWidgets.QLabel(self.groupBox_7)
        self.label.setGeometry(QtCore.QRect(20, 330, 131, 20))
        self.label.setObjectName("label")
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(860, 460, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "HW1"))
        self.groupBox.setTitle(_translate("Dialog", "1. Image Processing"))
        self.button1_1.setText(_translate("Dialog", "1.1 Load Image"))
        self.button1_2.setText(_translate("Dialog", "1.2 Color Conversion"))
        self.button1_3.setText(_translate("Dialog", "1.3 Image Flipping"))
        self.button1_4.setText(_translate("Dialog", "1.4 Blending"))
        self.groupBox_2.setTitle(_translate("Dialog", "2. Adaptive Threshold"))
        self.button2_1.setText(_translate("Dialog", "2.1 Global Threshold"))
        self.button2_2.setText(_translate("Dialog", "2.2 Local Threshold"))
        self.groupBox_3.setTitle(_translate("Dialog", "3. Image Transformation"))
        self.groupBox_4.setTitle(_translate("Dialog", "3.1 Rot, Scale, Translate"))
        self.groupBox_5.setTitle(_translate("Dialog", "Parameters"))
        self.label_2.setText(_translate("Dialog", "Angle: "))
        self.label_3.setText(_translate("Dialog", "Scale: "))
        self.label_4.setText(_translate("Dialog", "Tx: "))
        self.label_5.setText(_translate("Dialog", "Ty:"))
        self.label_6.setText(_translate("Dialog", "deg"))
        self.label_7.setText(_translate("Dialog", "pixel"))
        self.label_8.setText(_translate("Dialog", "pixel"))
        self.button3_1.setText(_translate("Dialog", "3.1 Rotation, Scaling, Translation"))
        self.button3_2.setText(_translate("Dialog", "3.2 Perspective Transform"))
        self.groupBox_6.setTitle(_translate("Dialog", "4. Convolution"))
        self.button4_1.setText(_translate("Dialog", "1. Gaussian"))
        self.button4_2.setText(_translate("Dialog", "2. SobelX"))
        self.button4_3.setText(_translate("Dialog", "3. SobelY"))
        self.button4_4.setText(_translate("Dialog", "4. Magnitude"))
        self.groupBox_7.setTitle(_translate("Dialog", "5."))
        self.button5_1.setText(_translate("Dialog", "5.1 Show Train Images"))
        self.button5_4.setText(_translate("Dialog", "5.4 Show Training Result"))
        self.button5_2.setText(_translate("Dialog", "5.2 Show Hyperparameters"))
        self.button5_3.setText(_translate("Dialog", "5.3 Train 1 Epoch"))
        self.button5_5.setText(_translate("Dialog", "5.5 Inference"))
        self.label.setText(_translate("Dialog", "Test Image Index:"))

